const Layout = () => import("@/layout/index.vue");
export default {
  path: "/quality/finished-product",
  component: Layout,
  redirect: "noredirect",
  meta: { title: "成品检验", icon: "caigou" },
  children: [
    {
      path: "liquid",
      component: () => import("@/views/quality/finished-product/liquid/index.vue"),
      name: "FinishedProductLiquid",
      meta: { title: "液体糖检验报告", icon: "caigou", keepAlive: true },
    },
    {
      path: "liquid/add",
      component: () => import("@/views/quality/finished-product/liquid/add.vue"),
      name: "FinishedProductLiquidAdd",
      meta: {
        title: "新建液体糖检验报告",
        icon: "caigou",
        keepAlive: true,
        hidden: true,
        activeMenu: "/quality/finished-product/liquid",
      },
    },
    {
      path: "saccharic-acid",
      component: () => import("@/views/quality/finished-product/saccharic-acid/index.vue"),
      name: "FinishedProductSaccharicAcid",
      meta: { title: "成品糖酸检验报告", icon: "caigou", keepAlive: true },
    },
    {
      path: "saccharic-acid/add",
      component: () => import("@/views/quality/finished-product/saccharic-acid/add.vue"),
      name: "FinishedProductSaccharicAcidAdd",
      meta: {
        title: "新建成品糖酸检验报告",
        icon: "caigou",
        keepAlive: true,
        hidden: true,
        activeMenu: "/quality/finished-product/saccharic-acid",
      },
    },

    {
      path: "microorganism",
      component: () => import("@/views/quality/finished-product/microorganism/index.vue"),
      name: "FinishedProductMicroorganism",
      meta: { title: "理化及微生物检验报告", icon: "caigou", keepAlive: true },
    },
    {
      path: "microorganism/add",
      component: () => import("@/views/quality/finished-product/microorganism/add.vue"),
      name: "FinishedProductMicroorganismAdd",
      meta: {
        title: "新建理化及微生物检验报告",
        icon: "caigou",
        keepAlive: true,
        hidden: true,
        activeMenu: "/quality/finished-product/microorganism",
      },
    },
    {
      path: "ingredient",
      component: () => import("@/views/quality/finished-product/ingredient/index.vue"),
      name: "FinishedProductIngredient",
      meta: { title: "Brix、pH成分分析报告", icon: "caigou", keepAlive: true },
    },
    {
      path: "ingredient/add",
      component: () => import("@/views/quality/finished-product/ingredient/add.vue"),
      name: "FinishedProductIngredientAdd",
      meta: {
        title: "新建Brix、pH成分分析报告",
        icon: "caigou",
        keepAlive: true,
        hidden: true,
        activeMenu: "/quality/finished-product/ingredient",
      },
    },
    {
      path: "finished-seam",
      component: () => import("@/views/quality/finished-product/finished-seam/index.vue"),
      name: "FinishedProductFinishedSeam",
      meta: { title: "成品卷封检验报告", icon: "caigou", keepAlive: true },
    },
    {
      path: "finished-seam/add",
      component: () => import("@/views/quality/finished-product/finished-seam/add.vue"),
      name: "FinishedProductFinishedSeamAdd",
      meta: {
        title: "新建成品卷封检验报告",
        icon: "caigou",
        keepAlive: true,
        hidden: true,
        activeMenu: "/quality/finished-product/finished-seam",
      },
    },
    {
      path: "identify",
      component: () => import("@/views/quality/finished-product/identify/index.vue"),
      name: "FinishedProductIdentify",
      meta: { title: "成品标签标识报告", icon: "caigou", keepAlive: true },
    },
    {
      path: "identify/add",
      component: () => import("@/views/quality/finished-product/identify/add.vue"),
      name: "FinishedProductIdentifyAdd",
      meta: {
        title: "新建成品标签标识报告",
        icon: "caigou",
        keepAlive: true,
        hidden: true,
        activeMenu: "/quality/finished-product/identify",
      },
    },
    {
      path: "finished-qrcode",
      component: () => import("@/views/quality/finished-product/finished-qrcode/index.vue"),
      name: "FinishedProductFinishedQrcode",
      meta: { title: "成品二维码确认单", icon: "caigou", keepAlive: true },
    },
    {
      path: "finished-qrcode/add",
      component: () => import("@/views/quality/finished-product/finished-qrcode/add.vue"),
      name: "FinishedProductFinishedQrcodeAdd",
      meta: {
        title: "新建成品二维码确认单",
        icon: "caigou",
        keepAlive: true,
        hidden: true,
        activeMenu: "/quality/finished-product/finished-qrcode",
      },
    },
    {
      path: "redbull",
      component: () => import("@/views/quality/finished-product/redbull/index.vue"),
      name: "FinishedProductRedbull",
      meta: { title: "红牛成品检验结果", icon: "caigou", keepAlive: true },
    },
    {
      path: "redbull/add",
      component: () => import("@/views/quality/finished-product/redbull/add.vue"),
      name: "FinishedProductRedbullAdd",
      meta: {
        title: "新建红牛成品检验结果",
        icon: "caigou",
        keepAlive: true,
        hidden: true,
        activeMenu: "/quality/finished-product/redbull",
      },
    },
    {
      path: "war-horse",
      component: () => import("@/views/quality/finished-product/war-horse/index.vue"),
      name: "FinishedProductWarHorse",
      meta: { title: "战马成品检验结果", icon: "caigou", keepAlive: true },
    },
    {
      path: "war-horse/add",
      component: () => import("@/views/quality/finished-product/war-horse/add.vue"),
      name: "FinishedProductWarHorseAdd",
      meta: {
        title: "新建战马成品检验结果",
        icon: "caigou",
        keepAlive: true,
        hidden: true,
        activeMenu: "/quality/finished-product/war-horse",
      },
    },
    {
      path: "notice",
      component: () => import("@/views/quality/finished-product/notice/index.vue"),
      name: "FinishedProductNotice",
      meta: { title: "成品发货通知单", icon: "caigou", keepAlive: true },
    },
    {
      path: "notice/add",
      component: () => import("@/views/quality/finished-product/notice/add.vue"),
      name: "FinishedProductNoticeAdd",
      meta: {
        title: "新建成品发货通知单",
        icon: "caigou",
        keepAlive: true,
        hidden: true,
        activeMenu: "/quality/finished-product/notice",
      },
    },
  ],
} as RouteConfigsTable;
