const Layout = () => import("@/layout/index.vue");
export default {
  path: "/quality/process-inspection",
  component: Layout,
  redirect: "noredirect",
  meta: { title: "工序检验", icon: "caigou" },
  children: [
    {
      path: "semi-product",
      component: () => import("@/views/quality/process-inspection/semi-product/index.vue"),
      name: "ProcessInspectionSemiProduct",
      meta: {
        title: "半成品检验报告",
        icon: "caigou",
        keepAlive: true,
      },
    },
    {
      path: "semi-product/add",
      component: () => import("@/views/quality/process-inspection/semi-product/add.vue"),
      name: "ProcessInspectionSemiProductAdd",
      meta: {
        title: "新建半成品检验报告",
        icon: "caigou",
        keepAlive: true,
        hidden: true,
        activeMenu: "/quality/process-inspection/semi-product",
      },
    },
    {
      path: "sample",
      component: () => import("@/views/quality/process-inspection/sample/index.vue"),
      name: "ProcessInspectionSample",
      meta: { title: "样品检验报告", icon: "caigou", keepAlive: true },
    },
    {
      path: "sample/add",
      component: () => import("@/views/quality/process-inspection/sample/add.vue"),
      name: "ProcessInspectionSampleAdd",
      meta: {
        title: "新建样品检验报告",
        icon: "caigou",
        keepAlive: true,
        hidden: true,
        activeMenu: "/quality/process-inspection/sample",
      },
    },
    {
      path: "control",
      component: () => import("@/views/quality/process-inspection/control/index.vue"),
      name: "ProcessInspectionControl",
      meta: { title: "工序控制检验报告", icon: "caigou", keepAlive: true },
    },
    {
      path: "control/add",
      component: () => import("@/views/quality/process-inspection/control/add.vue"),
      name: "ProcessInspectionControlAdd",
      meta: {
        title: "新建工序控制检验报告",
        icon: "caigou",
        keepAlive: true,
        hidden: true,
        activeMenu: "/quality/process-inspection/control",
      },
    },
    {
      path: "weigh",
      component: () => import("@/views/quality/process-inspection/weigh/index.vue"),
      name: "ProcessInspectionWeigh",
      meta: { title: "空罐顶盖重量检测", icon: "caigou", keepAlive: true },
    },
    {
      path: "weigh/add",
      component: () => import("@/views/quality/process-inspection/weigh/add.vue"),
      name: "ProcessInspectionWeighAdd",
      meta: {
        title: "新建空罐顶盖重量检测",
        icon: "caigou",
        keepAlive: true,
        hidden: true,
        activeMenu: "/quality/process-inspection/weigh",
      },
    },
    {
      path: "out-code",
      component: () => import("@/views/quality/process-inspection/out-code/index.vue"),
      name: "ProcessInspectionOutCode",
      meta: { title: "外箱二维码信息检测表", icon: "caigou", keepAlive: true },
    },
    {
      path: "out-code/add",
      component: () => import("@/views/quality/process-inspection/out-code/add.vue"),
      name: "ProcessInspectionOutCodeAdd",
      meta: {
        title: "新建外箱二维码信息检测表",
        icon: "caigou",
        keepAlive: true,
        hidden: true,
        activeMenu: "/quality/process-inspection/out-code",
      },
    },
    {
      path: "cip",
      component: () => import("@/views/quality/process-inspection/cip/index.vue"),
      name: "ProcessInspectionCip",
      meta: {
        title: "定期CIP检测项目",
        icon: "caigou",
        keepAlive: true,
      },
    },
    {
      path: "cip/add",
      component: () => import("@/views/quality/process-inspection/cip/add.vue"),
      name: "ProcessInspectionCipAdd",
      meta: {
        title: "新建定期CIP检测项目",
        icon: "caigou",
        keepAlive: true,
        hidden: true,
        activeMenu: "/quality/process-inspection/cip",
      },
    },
    {
      path: "stop",
      component: () => import("@/views/quality/process-inspection/stop/index.vue"),
      name: "ProcessInspectionStop",
      meta: { title: "停机及CIP检测项目", icon: "caigou", keepAlive: true },
    },
    {
      path: "stop/add",
      component: () => import("@/views/quality/process-inspection/stop/add.vue"),
      name: "ProcessInspectionStopAdd",
      meta: {
        title: "新建停机及CIP检测项目",
        icon: "caigou",
        keepAlive: true,
        hidden: true,
        activeMenu: "/quality/process-inspection/stop",
      },
    },
    {
      path: "start",
      component: () => import("@/views/quality/process-inspection/start/index.vue"),
      name: "ProcessInspectionStart",
      meta: { title: "开机确认单", icon: "caigou", keepAlive: true },
    },
    {
      path: "start/add",
      component: () => import("@/views/quality/process-inspection/start/add.vue"),
      name: "ProcessInspectionStartAdd",
      meta: {
        title: "新建开机确认单",
        icon: "caigou",
        keepAlive: true,
        hidden: true,
        activeMenu: "/quality/process-inspection/start",
      },
    },
    {
      path: "calibration",
      component: () => import("@/views/quality/process-inspection/calibration/index.vue"),
      name: "ProcessInspectionCalibration",
      meta: { title: "PH计校准表", icon: "caigou", keepAlive: true },
    },
    {
      path: "cip-microbes",
      component: () => import("@/views/quality/process-inspection/cip-microbes/index.vue"),
      name: "ProcessInspectionCipMicrobes",
      meta: { title: "CIP微生物检验报告", icon: "caigou", keepAlive: true },
    },
    {
      path: "cip-microbes/add",
      component: () => import("@/views/quality/process-inspection/cip-microbes/add.vue"),
      name: "ProcessInspectionCipMicrobesAdd",
      meta: {
        title: "新建CIP微生物检验",
        icon: "caigou",
        keepAlive: true,
        hidden: true,
        activeMenu: "/quality/process-inspection/cip-microbes",
      },
    },
    {
      path: "water-microbes",
      component: () => import("@/views/quality/process-inspection/water-microbes/index.vue"),
      name: "ProcessInspectionWaterMicrobes",
      meta: { title: "水处理微生物检验报告", icon: "caigou", keepAlive: true },
    },
    {
      path: "water-microbes/add",
      component: () => import("@/views/quality/process-inspection/water-microbes/add.vue"),
      name: "ProcessInspectionWaterMicrobesAdd",
      meta: {
        title: "新建水处理微生物检验",
        icon: "caigou",
        keepAlive: true,
        hidden: true,
        activeMenu: "/quality/process-inspection/water-microbes",
      },
    },
  ],
} as RouteConfigsTable;
