const Layout = () => import('@/layout/index.vue')

export default {
  name: 'enjoyGift',
  path: '/',
  component: Layout,
  redirect: '/workbench',
  meta: {
    title: '天天享礼',
    icon: 'teenyicons:gift-solid',
    requireAuth: false,
    order: 2,
  },
  children: [
    {
      name: 'homeManageList',
      path: 'home-manage-list',
      component: () => import('@/views/enjoy-gift/home-manage/index.vue'),
      meta: {
        title: '首页管理',
        icon: 'fa6-regular:building',
        order: 1,
        requireAuth: false,
      },
      children: [
        {
          name: 'imgTextManage',
          path: 'imgText-manage/list',
          component: () => import('@/views/enjoy-gift/home-manage/imgText-manage/index.vue'),
          meta: {
            title: '图文管理(非会员)',
            icon: 'fa6-regular:images',
            keepAlive: true,
            order: 1,
            requireAuth: true,
            role: ['popover_2_getlist_1'],
          },
        },
        {
          name: 'imgTextManageNotVip',
          path: 'imgText-manage_notVip/list',
          component: () => import('@/views/enjoy-gift/home-manage/imgText-manage_notVip/index.vue'),
          meta: {
            title: '图文管理(会员)',
            icon: 'fa6-regular:images',
            keepAlive: true,
            order: 1,
            requireAuth: true,
            role: ['popover_2_getlist_1'],
          },
        },
        {
          name: 'RankingList',
          path: 'ranking/list',
          component: () => import('@/views/enjoy-gift/home-manage/ranking-list/index.vue'),
          meta: {
            title: '排行榜',
            icon: 'fa6-regular:chart-bar',
            keepAlive: true,
            order: 2,
            requireAuth: true,
            role: ['layout_gettoplist_1'],
          },
        },
        {
          name: 'SingleColumnDiagram',
          path: 'singleColumnDiagram',
          component: () => import('@/views/enjoy-gift/home-manage/single-column-diagram/index.vue'),
          meta: {
            title: '单例图',
            icon: 'fa6-regular:image',
            keepAlive: true,
            order: 3,
            requireAuth: true,
            role: ['layout_getsingleimagelist_1'],
          },
        },
        {
          name: 'TimeLimitSeckillList',
          path: 'list',
          component: () => import('@/views/enjoy-gift/home-manage/time-limit-seckill/index.vue'),
          meta: {
            title: '限时秒杀',
            icon: 'material-symbols:timer',
            order: 4,
            keepAlive: true,
            requireAuth: true,
            role: ['activity_getseckilllist_1'],
          },
        },
        {
          name: 'CouponGroup',
          path: 'couponGroup/list',
          component: () => import('@/views/enjoy-gift/home-manage/coupon-group/index.vue'),
          meta: {
            title: '优惠券分组',
            icon: 'uis:grid',
            keepAlive: true,
            order: 5,
            requireAuth: true,
            role: ['coupon_getgrouplist_1'],
          },
        },
        {
          name: 'redPacket',
          path: 'redPacket',
          component: () => import('@/views/enjoy-gift/home-manage/red-packet/index.vue'),
          meta: {
            title: '外卖红包',
            icon: 'icon-park-outline:coupon',
            keepAlive: true,
            order: 6,
            requireAuth: true,
            role: ['take_takexq_1'],
          },
        },
        {
          name: 'chargeGroup',
          path: 'chargeGroup',
          component: () => import('@/views/enjoy-gift/home-manage/chargeGroup/index.vue'),
          meta: {
            title: '大牌直充',
            icon: 'icon-park-outline:charging-treasure',
            keepAlive: true,
            order: 7,
            requireAuth: true,
            role: ['take_categorylist_1'],
          },
        },
        {
          name: 'recommendGroup',
          path: 'recommendGroup',
          component: () => import('@/views/enjoy-gift/home-manage/recommend-group/index.vue'),
          meta: {
            title: '弹窗推荐商品',
            icon: 'pajamas:list-indent',
            keepAlive: true,
            order: 8,
            requireAuth: true,
            role: ['popover_scorelist_1'],
          },
        },
        {
          name: 'repairGroup',
          path: 'repairGroup',
          component: () => import('@/views/enjoy-gift/home-manage/repair-group/index.vue'),
          meta: {
            title: '捡漏专区',
            icon: 'fa6-regular:clock',
            keepAlive: true,
            order: 9,
            requireAuth: true,
            role: ['popover_leaklist_1'],
          },
        },
        /*{
          name: 'CarouselManage',
          path: 'carousel-manage/list',
          component: () =>
              import ('@/views/enjoy-gift/home-manage/carousel-manage/index.vue'),
          meta: {
              title: '轮播管理',
              icon: 'material-symbols:code-blocks-rounded',
              keepAlive: true,
              order: 102,
          },
      },*/
        {
          name: 'zeroCoupon',
          path: 'zeroCoupon',
          component: () => import('@/views/enjoy-gift/home-manage/zero-coupon/index.vue'),
          meta: {
            title: '零豆专区',
            icon: 'fa6-regular:clock',
            keepAlive: true,
            order: 10,
            requireAuth: true,
            role: ['zero_getlist_1'],
          },
        },
      ],
    },
    {
      name: 'taskGroupList',
      path: 'task-group-list',
      component: () => import('@/views/enjoy-gift/task-group/index.vue'),
      meta: {
        title: '任务管理',
        icon: 'fa6-regular:star-half-stroke',
        order: 2,
        requireAuth: false,
      },
      children: [
        {
          name: 'TaskMangeList',
          path: 'taskMange/list',
          component: () => import('@/views/enjoy-gift/task-group/task-mange/index.vue'),
          meta: {
            title: '任务列表',
            icon: 'fa-solid:tasks',
            order: 96,
            keepAlive: true,
            requireAuth: true,
            role: ['task_getlist_1'],
          },
        },
        {
          name: 'TimeLimitCouponList',
          path: 'timeLimitCoupon/list',
          component: () => import('@/views/enjoy-gift/task-group/time-limit-coupon/index.vue'),
          meta: {
            title: '限时领券',
            icon: 'ic:twotone-access-time-filled',
            order: 97,
            keepAlive: true,
            requireAuth: true,
            role: ['activity_getcouponlist_1'],
          },
        },
      ],
    },
    {
      name: 'ShopGroup',
      path: 'shopGroup/list',
      component: () => import('@/views/enjoy-gift/shop-group/index.vue'),
      meta: {
        title: '电商分组',
        icon: 'uis:grid',
        keepAlive: true,
        order: 3,
        requireAuth: true,
        role: ['jd_getlist_1'],
      },
    },
    {
      name: 'CouponList',
      path: 'coupon/list',
      component: () => import('@/views/enjoy-gift/coupon-list/index.vue'),
      meta: {
        title: '优惠券列表',
        icon: 'ri:coupon-3-fill',
        keepAlive: true,
        order: 4,
        requireAuth: true,
        role: ['coupon_getlist_1'],
      },
    },
    {
      name: 'goodsManageList',
      path: 'goods-manage-list',
      component: () => import('@/views/enjoy-gift/goods-manage/index.vue'),
      meta: {
        title: '商品管理',
        icon: 'icon-park-solid:commodity',
        order: 5,
        requireAuth: false,
      },
      children: [
        {
          name: 'GoodsList',
          path: 'goods/list',
          component: () => import('@/views/enjoy-gift/goods-manage/goods-list/index.vue'),
          meta: {
            title: '商品列表',
            icon: 'icon-park-outline:coupon',
            requireAuth: true,
            role: ['goods_getlist_1'],
          },
        },
        {
          name: 'JDGoodsList',
          path: 'JDgoods/list',
          component: () => import('@/views/enjoy-gift/goods-manage/JDgoods-list/index.vue'),
          meta: {
            title: '京东商品',
            icon: 'ep:goods-filled',
            requireAuth: false,
          },
        },
        {
          name: 'hwGoodsList',
          path: 'hwGoods/list',
          component: () => import('@/views/enjoy-gift/goods-manage/HWGoods-list/index.vue'),
          meta: {
            title: '惠吃喝商品',
            icon: 'majesticons:burger-line',
            requireAuth: true,
            role: ['hw_goodslist_1'],
          },
        },
        {
          name: 'themeGoods',
          path: 'themeGoods/list',
          component: () => import('@/views/enjoy-gift/goods-manage/themeGoods-list/index.vue'),
          meta: {
            title: '商品专题',
            icon: 'material-symbols:joystick-outline-sharp',
            requireAuth: true,
            role: ['goodstheme_getlist_1'],
          },
        },
      ],
    },
    {
      name: 'Popover',
      path: 'popover/list',
      component: () => import('@/views/enjoy-gift/popover/index.vue'),
      meta: {
        title: '弹窗管理',
        icon: 'fa6-regular:window-restore',
        order: 105,
        keepAlive: true,
        requireAuth: true,
        role: ['popover_1_getlist_1'],
      },
    },
    {
      name: 'OrderList',
      path: 'orderMange/list',
      component: () => import('@/views/enjoy-gift/order-manage/index.vue'),
      meta: {
        title: '订单列表',
        icon: 'icon-park-solid:align-text-both-one',
        order: 106,
        keepAlive: true,
        requireAuth: true,
        role: ['order_getlist_1'],
      },
    },
    {
      name: 'SavingList',
      path: 'savingMange/list',
      component: () => import('@/views/enjoy-gift/saving-manage/index.vue'),
      meta: {
        title: '省钱卡订单',
        icon: 'icon-park-solid:align-text-both-one',
        order: 107,
        keepAlive: true,
        requireAuth: true,
        role: ['saving_getlist_1'],
      },
    },
    {
      name: 'siteManageList',
      path: 'site-manage-list',
      component: () => import('@/views/enjoy-gift/site-group/index.vue'),
      meta: {
        title: '系统设置',
        icon: 'material-symbols:brightness-7-rounded',
        order: 108,
        requireAuth: false,
      },
      children: [
        {
          name: 'Share',
          path: 'share/list',
          component: () => import('@/views/enjoy-gift/site-group/share/index.vue'),
          meta: {
            title: '分享图文',
            icon: 'fa6-regular:share-from-square',
            order: 1,
            keepAlive: true,
            requireAuth: true,
            role: ['popover_3_getlist_1'],
          },
        },
        {
          name: 'SiteConfig',
          path: 'site-config/list',
          component: () => import('@/views/enjoy-gift/site-group/site-config/index.vue'),
          meta: {
            title: '公众号回复',
            icon: 'fa6-regular:comment-dots',
            order: 2,
            keepAlive: true,
            requireAuth: true,
            role: ['jd_sitelist_1'],
          },
        },
        {
          name: 'keywordConfig',
          path: 'site-keyword/list',
          component: () => import('@/views/enjoy-gift/site-group/site-keyword/index.vue'),
          meta: {
            title: '搜索关键词',
            icon: 'ic:round-manage-search',
            order: 3,
            keepAlive: true,
            requireAuth: true,
            role: ['jd_getkeywordlist_1'],
          },
        },
        {
          name: 'ruleConfig',
          path: 'price-rule/list',
          component: () => import('@/views/enjoy-gift/site-group/price-rule/index.vue'),
          meta: {
            title: '海威价格',
            icon: 'ic:twotone-currency-yen',
            order: 4,
            keepAlive: true,
            requireAuth: true,
            role: ['hw_getlist_1'],
          },
        },
        {
          name: 'shopImg',
          path: 'shop-img/index',
          component: () => import('@/views/enjoy-gift/site-group/shop-img/index.vue'),
          meta: {
            title: '彬纷享礼配置',
            icon: 'charm:home',
            order: 5,
            keepAlive: true,
            requireAuth: true,
            role: ['popover_scorexq_1'],
          },
        },
        {
          name: 'storeImg',
          path: 'store-img/index',
          component: () => import('@/views/enjoy-gift/site-group/store-img/index.vue'),
          meta: {
            title: '惠吃喝门店时段',
            icon: 'fa6-regular:image',
            order: 6,
            keepAlive: true,
            requireAuth: true,
            role: ['popover_4_getlist_1'],
          },
        },
        {
          name: 'eventNotice',
          path: 'event-notice/index',
          component: () => import('@/views/enjoy-gift/site-group/event-notice/index.vue'),
          meta: {
            title: '消息模板',
            icon: 'material-symbols:chat-paste-go-outline',
            order: 7,
            keepAlive: true,
            requireAuth: true,
            role: ['templete_getinfo_1'],
          },
        },
        /*{
                                          name: 'bfJd',
                                          path: 'bfJd/index',
                                          component: () => import('@/views/enjoy-gift/site-group/bfjd/index.vue'),
                                          meta: {
                                            title: '彬纷京东版块配置',
                                            icon: 'ep:goods-filled',
                                            order: 8,
                                            keepAlive: true,
                                            requireAuth: true,
                                            role: ['bfjd_getxq_1'],
                                          },
                                        },*/
        {
          name: 'scaleConfig',
          path: 'scale-rule/list',
          component: () => import('@/views/enjoy-gift/site-group/scale-rule/index.vue'),
          meta: {
            title: '分佣配置',
            icon: 'ic:twotone-currency-yen',
            order: 9,
            keepAlive: true,
            requireAuth: true,
            role: ['scale_getlist_1'],
          },
        },
      ],
    },
    // {
    //     name: 'benefitLift',
    //     path: 'benefit-ift',
    //     component: () =>
    //         import ('@/views/benefit-life/index.vue'),
    //     meta: {
    //         title: '惠生活',
    //         icon: 'icon-park-solid:shopping',
    //         order: 105,
    //         keepAlive: true,
    //     },
    //     children: [{
    //             name: 'filmList',
    //             path: 'film/list',
    //             component: () =>
    //                 import ('@/views/benefit-life/film-list/index.vue'),
    //             meta: {
    //                 title: '电影',
    //                 icon: 'icon-park-solid:commodity',
    //             },
    //         },
    //         {
    //             name: 'kfcList',
    //             path: 'kfc/list',
    //             component: () =>
    //                 import ('@/views/benefit-life/kfc-list/index.vue'),
    //             meta: {
    //                 title: '肯德基',
    //                 icon: 'icon-park-solid:commodity',
    //             },
    //         }
    //     ],
    // },

    // {
    //   name: 'coupon-group',
    //   path: 'couponGroup',
    //   component: Layout,
    //   redirect: '/couponGroup/list',
    //   meta: {
    //     title: '优惠券分组',
    //     order: 101,
    //   },
    //   children: [
    //     {
    //       name: 'CouponGroup',
    //       path: 'list',
    //       component: () => import('@/views/coupon-group/index.vue'),
    //       meta: {
    //         title: '优惠券分组',
    //         icon: 'uis:grid',
    //         keepAlive: true,
    //       },
    //     },
    //   ],
    // },
  ],
}
